### ISSUE TITLE
banner-cli adds banner to itself

### ISSUE THREAD

**Issue by kitsguru** [cjpatoilo/banner-cli#5] opened 2019-01-27 21:57 UTC
I am running banner-cli globally 

`banner-cli www/css/*.css`

However the files specified do not get processed and my banner is added to banner-cli itself causing it to fail on the next run.

Here is the output of running the command twice.

```
(master *%>)
13:59 > banner-cli "www/css/*.css"

(master *%>)
13:59 > banner-cli "www/css/*.css"
/usr/local/bin/banner-cli: line 1: /*!: No such file or directory
/usr/local/bin/banner-cli: line 2: CHANGE-LOG.md: command not found
/usr/local/bin/banner-cli: line 3: CHANGE-LOG.md: command not found
/usr/local/bin/banner-cli: line 4: CHANGE-LOG.md: command not found
/usr/local/bin/banner-cli: line 5: syntax error near unexpected token `('
/usr/local/bin/banner-cli: line 5: ` * Copyright (c) 2019 Jeff Shields'
```

npm --version
6.7.0

node --version
v11.7.0

**Comment by wolves** [comment] 2019-02-05 18:23
I am also having this same issue. If I have time I will try and find a fix and make a PR

**Comment by wolves** [comment] 2019-02-05 20:56
This is a duplicate of one of the only other 2 issues.

https://github.com/cjpatoilo/banner-cli/issues/2

It's good that you report issues @kitsguru but you should try to take a quick look at other current existing ones first before creating a new duplicate.

No big deal, it just helps OSS maintainers have a clear view of what's going on.

I am going to try and see if I can get a PR in yet today to help fix this for the package author

**Comment by kitsguru** [comment] 2019-02-07 03:46
I scanned the subjects but didn't take the time to ready each issue. #2 title really didn't reflect the issue I was having. I don't have time to ready every open issue to see if they are relevant. If there had been a number of open issues I would have done a search. The option would have been not to report it at all. But your point is taken and thanks for pointing that out.

Maybe editing the title of #2 to reflect the issue would also be a appropriate. That issue is also a year old and has not been addressed.

**Closed as completed** 2019-06-15 11:49 UTC
